### ISSUE TITLE
Readme changes, possibly?

### ISSUE THREAD

**Issue by cjm771** [rpt09-scully/trail-photos-service#4]
Hi Meng, 

Just two minor comments for possible README.md adjustments.  after getting your dev setup.

1) i would say for your. env-sample i would just include  your name for db, as its not sensitive info and will help future installers to not have that hiccup. 

```
HOST=
DATABASE=trailPhotosDB
DBPORT=
```

2) The other is for starting your server I would say the public facing command should be `startWeb` in your case, bc i realized the `npm start` also starts up your react watch and opens a page which for the other team members we dont want to start. So maybe thats also an edit in your readme.

**Comment by MengRS** [comment]
Thank you @cjm771! I concur with your suggestions and have made the adjustments.
