### ISSUE TITLE
Generate Valid Mock Photos

### ISSUE THREAD

**Issue by MengRS** [rpt09-scully/trail-photos-service#6]
As a user, I would like to be able to see valid mock photos as placeholders so that I can have a visual idea of what the trail-photos component would look like.

**Issue**: The original LoremFlickr.com TTL for their cache was 24 hours or less and therefore, mock photo links generated by LoremFlickr.com threw a 404.

**Impact**: All users of the trail-photos service will not be able to render valid trail-photos.

**Requirements**:
- [x] Generate photos for the mock database that have no cache or longer TTL (> 1 month).
- [x] Actual mock photos (like all mock data), should have the opportunity to be consistent amongst all users.
- [x] If possible, photos should be nature-themed.

**Comment by MengRS** [comment]
Looked into lorempixel.com but found the site was slow and did not re-direct to a different url (which would not fulfill the requirements).

Unfortunately, using webscraper.io was not an option for photos on the alltrails site due to alltrails's html layout.

Decision: Went with unsplash.com (from the looks of things, there does not seem to be a cache affiliated with their generated urls) - however, I can't be so sure until time passes. 

Other Possibilities:

- Use webscraper.io on a nature gallery found on another (yet to be determined) site.

- De-prioritize certain requirements.

**Comment by adrianodantasit** [comment]
Hi @MengRS.
Check this page: [https://picsum.photos/](https://picsum.photos/) 
I hope it helps you in your project.

**Comment by MengRS** [comment]
@adrianodantasit, thank you - unfortunately, [picsum.photos](https://picsum.photos/) does not give you the ability to search for `nature` themed photos in particular - but I'll definitely keep it in mind in case requirements change.

**Comment by adrianodantasit** [comment]
You're welcome @MengRS, I see you changed to unsplash, I believe you can't go wrong with it, their API allow that.

**Comment by MengRS** [comment]
used unsplash
